# LawFirmAI Gradio Docker Compose
# Local development environment for Gradio interface

version: '3.8'

services:
  lawfirm-gradio:
    build: .
    ports:
      - "7860:7860"  # Gradio interface
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:///./data/lawfirm.db
      - CHROMA_DB_PATH=./data/chroma_db
      - LOG_LEVEL=DEBUG
      - DEBUG=true
    volumes:
      - ../data:/app/data
      - ../models:/app/models
      - ../logs:/app/logs
      - ../model_cache:/app/model_cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
