# 법령용어 수집 설정 파일
# LawFirmAI 프로젝트의 법령용어 주기적 수집 시스템 설정

# 수집 설정
collection:
  enabled: true
  data_type: "legal_terms"
  
  # 스케줄링 설정
  scheduling:
    # 일일 수집 설정
    daily_collection:
      enabled: true
      time: "02:00"  # 매일 오전 2시
      timeout_minutes: 30
      max_retries: 3
      retry_delay: 5
    
    # 주간 전체 동기화 설정
    weekly_full_sync:
      enabled: false  # 기본적으로 비활성화 (필요시 활성화)
      day: "sunday"   # 매주 일요일
      time: "01:00"   # 오전 1시
      timeout_minutes: 60
      max_retries: 3
      retry_delay: 10

# API 설정
api:
  base_url: "http://www.law.go.kr/DRF/lawSearch.do"
  timeout: 30
  max_retries: 3
  retry_delay: 5
  min_request_interval: 1.0  # 최소 요청 간격 (초) - 서버 과부하 방지
  page_size: 100  # 페이지당 항목 수
  max_pages: null  # 최대 페이지 수 (null이면 모든 페이지)

# 데이터 저장 설정
data_storage:
  # 데이터 디렉토리
  data_dir: "data/raw/law_open_api/legal_terms"
  metadata_dir: "data/raw/law_open_api/metadata"
  
  # 백업 설정
  backup:
    enabled: true
    backup_count: 5  # 백업 파일 수
    backup_interval_days: 7  # 백업 간격 (일)
  
  # 정리 설정
  cleanup:
    enabled: true
    keep_days: 30  # 보관할 일수
    cleanup_interval_days: 7  # 정리 간격 (일)

# 로깅 설정
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  log_dir: "logs/legal_term_collection"
  max_file_size_mb: 10
  backup_count: 5
  
  # 로그 타입별 설정
  collection_log:
    enabled: true
    filename: "collection_%Y%m%d.log"
  
  scheduler_log:
    enabled: true
    filename: "scheduler_%Y%m%d.log"
  
  error_log:
    enabled: true
    filename: "errors_%Y%m%d.log"

# 모니터링 설정
monitoring:
  enabled: true
  
  # 상태 체크 설정
  status_check:
    enabled: true
    interval_minutes: 60  # 상태 체크 간격
  
  # 알림 설정 (향후 확장용)
  notifications:
    enabled: false
    email:
      enabled: false
      smtp_server: ""
      smtp_port: 587
      username: ""
      password: ""
      recipients: []
    
    slack:
      enabled: false
      webhook_url: ""
      channel: "#lawfirmai-alerts"
    
    webhook:
      enabled: false
      url: ""
      timeout: 30

# 성능 설정
performance:
  # 메모리 관리
  memory:
    max_memory_mb: 1024
    cleanup_threshold: 0.8  # 메모리 사용률 80%에서 정리
  
  # 배치 처리
  batch:
    size: 10  # 배치 크기
    delay_min: 0.1  # 최소 지연 시간 (초)
    delay_max: 0.5  # 최대 지연 시간 (초)
  
  # 병렬 처리
  parallel:
    enabled: false  # 기본적으로 비활성화 (API 제한 고려)
    max_workers: 3
    timeout: 30

# 보안 설정
security:
  # API 키 관리
  api_key:
    env_var: "LAW_OPEN_API_OC"  # 환경변수 이름
    required: true
  
  # 요청 제한
  rate_limiting:
    enabled: true
    requests_per_minute: 60
    requests_per_hour: 1000
  
  # 데이터 보호
  data_protection:
    encrypt_sensitive_data: false  # 향후 확장용
    backup_encryption: false

# 개발/테스트 설정
development:
  # 테스트 모드
  test_mode:
    enabled: false
    mock_data: false
    sample_size: 10
  
  # 디버그 설정
  debug:
    enabled: false
    verbose_logging: false
    api_response_logging: false
  
  # 개발용 설정
  dev_settings:
    skip_api_calls: false
    use_cached_data: false
    cache_dir: "cache/dev"

# 환경별 설정 오버라이드
environments:
  development:
    logging:
      level: "DEBUG"
    api:
      timeout: 60
    monitoring:
      enabled: false
  
  production:
    logging:
      level: "INFO"
    api:
      timeout: 30
    monitoring:
      enabled: true
    performance:
      parallel:
        enabled: true
  
  testing:
    logging:
      level: "WARNING"
    api:
      timeout: 10
    development:
      test_mode:
        enabled: true




